/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "BetterObjectValidator"
include(":annotation-user")
include(":annotation-processor")
