/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("groupId.java-conventions")
}

dependencies {
    implementation("org.hamcrest:hamcrest-all:1.3")
    implementation("com.samskivert:jmustache:1.15")
    implementation("com.google.guava:guava:31.1-jre")
    compileOnly("com.google.auto.service:auto-service:1.0.1")
}

description = "annotation-processor"
